# Uncomment this line to define a global platform for your project
platform :ios, '6.0'

pod 'MSPageViewController', '~> 1.0.0'

target 'YesForEquality' do

end

target 'YesForEqualityTests' do

end

